id: AAEBCDA1B
title: Fulfilment Offering for Nyangrel Nyima Özer's Treasure Practice of Black Hayagrīva
  with an Iron Sword
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:15:19.597669
  last_modified_at: 2022-02-28 23:15:19.597672
