id: AAEBCDA1B
title: 'The Swift Fulfilment of Wishes: A Prayer for the Swift Return of the Supreme
  Tulku of the Fifth Drubwang Dzogchen Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:15:19.599387
  last_modified_at: 2022-02-28 23:15:19.599391
