id: AAEBCDA1B
title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:15:19.594518
  last_modified_at: 2022-02-28 23:15:19.594526
